Rails.application.routes.draw do
  resources :toys
  root "toys#main"

  get 'contakt', to: 'toys#contakt'
  get 'razr', to: 'toys#razr'
  get 'shumelki', to: 'toys#shumelki'
  get 'pyramid', to: 'toys#pyramid'
  get 'lacing', to: 'toys#lacing'
  get 'puzzlespictures', to: 'toys#puzzlespictures'
  get 'looseleaves', to: 'toys#looseleaves'
  get 'sorters', to: 'toys#sorters'
  get 'cubes', to: 'toys#cubes'
  get 'boardgames', to: 'toys#boardgames'
  get 'constructors', to: 'toys#constructors'
  get 'creatorskit', to: 'toys#creatorskit'
  get 'puzzles', to: 'toys#puzzles'
  get 'learningtoread', to: 'toys#learningtoread'
  get 'westudythealphabet', to: 'toys#westudythealphabet'
  get 'languageandcommunication', to: 'toys#languageandcommunication'
  get 'accounteducation', to: 'toys#accounteducation'
  get 'developmentoflogicalthinking', to: 'toys#developmentoflogicalthinking'
  get 'developmentofmemoryandattention', to: 'toys#developmentofmemoryandattention'
  get 'colorsandshapes', to: 'toys#colorsandshapes'
  get 'theworld', to: 'toys#theworld'
  get 'puzzlegames', to: 'toys#puzzlegames'
  get 'teaching', to: 'toys#teaching'
  get 'developing', to: 'toys#developing'
  get 'merry', to: 'toys#merry'
  get 'forthecompany', to: 'toys#forthecompany'
  get 'constructor', to: 'toys#constructor'
  get 'massformodeling', to: 'toys#massformodeling'
  get 'sandformodeling', to: 'toys#sandformodeling'
  get 'puzzle', to: 'toys#puzzle'
  get 'creation', to: 'toys#creation'
  get 'printedproducts', to: 'toys#printedproducts'
  get 'plaything', to: 'toys#plaything'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
